# .github/workflows/pacman.yml
name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12h (UTC)
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: pacman-graph
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@1.0.10.2
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Create dark variant
        shell: bash
        run: |
          set -euo pipefail
          test -f dist/pacman-contribution-graph.svg

          # Make dark copy
          cp dist/pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg

          # Recolor to GitHub Dark palette (tweak if your source palette differs)
          sed -i \
            -e 's/#ffffff/#0d1117/Ig' \
            -e 's/#fff/#0d1117/Ig' \
            -e 's/#e4e2e2/#30363d/Ig' \
            -e 's/#24292e/#c9d1d9/Ig' \
            -e 's/#000000/#c9d1d9/Ig' \
            dist/pacman-contribution-graph-dark.svg

          # Prepare assets/
          mkdir -p assets
          cp dist/pacman-contribution-graph.svg assets/pacman-contribution-graph.svg
          cp dist/pacman-contribution-graph-dark.svg assets/pacman-contribution-graph-dark.svg

          # Sanity checks
          test -s assets/pacman-contribution-graph.svg
          test -s assets/pacman-contribution-graph-dark.svg

      - name: Commit & push to main
        shell: bash
        run: |
          set -e
          git config user.name "readme-bot"
          git config user.email "actions@github.com"
          git add assets/pacman-contribution-graph*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update pacman graphs"
            git push origin HEAD:main
          fi
